production:
  adapter: postgresql
  pool: 5
  timeout: 5000
  encoding: utf8
  database: <%=ENV['OPENSHIFT_APP_NAME']%>
  username: <%=ENV['OPENSHIFT_POSTGRESQL_DB_USERNAME']%>
  password: <%=ENV['OPENSHIFT_POSTGRESQL_DB_PASSWORD']%>
  host: <%=ENV['OPENSHIFT_POSTGRESQL_DB_HOST']%>
  port: <%=ENV['OPENSHIFT_POSTGRESQL_DB_PORT']%>
  min_messages: ERROR
  reconnect: false

# You need to create the database locally
test:
  adapter: sqlite3
  encoding: utf8
  database: db/test.sqlite3
  pool: 5
  timeout: 5000

# You need to create the database locally
development:
  adapter: sqlite3
  encoding: utf8
  database: db/development.sqlite3
  pool: 5
  timeout: 5000